### ISSUE TITLE
touch boot/ssh

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/zero#4]
`touch boot/ssh
touch: boot/ssh: No such file or directory
make: *** [boot/ssh] Error 1`

/Volumes/boot exists

Maybe the Makefile tries to create `ssh` before /boot is mounted?

**Comment by meeDamian** [comment]
No, it's a temporary `./boot/` directory. I guess it's not created in time, and git just ignores empty directories 🤔. I'll fix it.
